import os, sys
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from env.env import EnvironmentManager
from utils.human_llm_config import HumanLLMConfig
from config import *

# Assume llmORchains_list is already defined in your project configuration.
from config import MODELS_CONFIG_LIST as llmORchains_list
config = HumanLLMConfig()
config.initialize()  # Initialize configuration if not already done
llmORchains_list = config.get_llmORchains_list()
config.common_vectordb_config.embedding_function = embedding_function

def test_GetFromLatex():
    # Define a list of documents with known targets (first version: arxiv JSON targets)
    documents = [
        {
            'id': "cf0d353c-b43b-4a79-88f9-42c2c84cf75e",
            'title': "Complex QA and language models hybrid architectures, Survey",
            'context': "Initial placeholder context for Complex QA...",  # Fill with a known placeholder if needed
            'target_file_path': "env/IR_CPS_TechSynthesis/document_embedding_analysis/output/arxiv/Complex QA and language models hybrid architectures Survey.json"
        },
        {
            'id': "42252c6c-12f3-4edf-9045-8acd69bc3356",
            'title': "Macroeconomic Effects of Inflation Targeting A Survey of the Empirical Literature",
            'context': "Initial placeholder context for Macroeconomic Effects...",  # Again, placeholder text
            'target_file_path': "env/IR_CPS_TechSynthesis/document_embedding_analysis/output/arxiv/Macroeconomic Effects of Inflation Targeting A Survey of the Empirical  Literature.json"
        }
    ]

    envs_tech_synthesis = []
    # Create environments using the arxiv JSON targets.
    for doc in documents:
        env = EnvironmentManager(
            env_type="techsynthesis",
            title=doc['title'],
            context=doc['context'],
            target_file_path=doc['target_file_path'],
            id=doc['id'],
            llm=llmORchains_list["default_llm"],
            embedding_model_name=config.common_vectordb_config.embedding_function
        ).get_environment()
        envs_tech_synthesis.append(env)

    print("== Initial Distance Scores (using arxiv targets) ==")
    for env in envs_tech_synthesis:
        # get_distance_to_targetJSON() is assumed to be defined on the environment.
        score = env.get_score() # get_distance_to_targetJSON()
        print(f"Env ID: {env.id} -- Distance Score: {score}")

    # Create second versions where the target_file_path points to the JSON files produced from LaTeX.
    # (i.e. they have been generated by GetFromLatex previously)
    latex_target_paths = [
        "env/IR_CPS_TechSynthesis/document_embedding_analysis/output/latex/Complex QA & language models hybrid architectures, Survey_with_embeddings.json",
        "env/IR_CPS_TechSynthesis/document_embedding_analysis/output/latex/Macroeconomic_Effects_of_Inflation_Targeting_A_Survey_of_the_Empirical__Literature_with_embeddings.json"
    ]
    envs_updated = []
    for doc, latex_target in zip(documents, latex_target_paths):
        env = EnvironmentManager(
            env_type="techsynthesis",
            title=doc['title'],
            context=doc['context'],
            target_file_path=latex_target,  # updated target
            id=doc['id'],
            llm=llmORchains_list["default_llm"],
            embedding_model_name=config.common_vectordb_config.embedding_function
        ).get_environment()
        envs_updated.append(env)

    # Load LaTeX and BibTeX content into the environments using GetFromLatex.
    # Define the file paths for the LaTeX and corresponding BibTeX files.
    # (Make sure these files exist in your data directory.)
    latex_files = [
        "Optuna_report_outputs/demo_human_sim_20250422_1422/intelligent_('analyst',)_Complex_QA_101f4a3a.tex",
        "env/IR_CPS_TechSynthesis/document_embedding_analysis/data/latex/Macroeconomic_Effects_of_Inflation_Targeting_A_Survey_of_the_Empirical__Literature.tex"
    ]
    bib_files = [
        "env/IR_CPS_TechSynthesis/document_embedding_analysis/data/latex/Complex QA & language models hybrid architectures, Survey.bib",
        "env/IR_CPS_TechSynthesis/document_embedding_analysis/data/latex/Macroeconomic_Effects_of_Inflation_Targeting_A_Survey_of_the_Empirical__Literature.bib"
    ]

    for env, tex_path, bib_path in zip(envs_updated, latex_files, bib_files):
        # Open and read the LaTeX file content.
        with open(tex_path, "r", encoding="utf-8") as f:
            latex_content = f.read()
        # Open and read the BibTeX file content.
        with open(bib_path, "r", encoding="utf-8") as f:
            bib_content = f.read()
        # Call GetFromLatex (assumed to be a method on env.synthesis_manager)
        env.synthesis_manager.GetFromLatex(latex_content, bib_file=bib_content)

    def filter_strings_only(obj, seen=None, depth=0, max_depth=2):
        if seen is None:
            seen = set()
        # Cycle detection: avoid processing the same object twice.
        if id(obj) in seen:
            return None
        seen.add(id(obj))
        
        # When the maximum depth is reached, only extract direct string values.
        if depth >= max_depth:
            if isinstance(obj, str):
                return obj
            elif isinstance(obj, dict):
                # Only keep key-value pairs where the value is a string.
                return {k: v for k, v in obj.items() if isinstance(v, str)}
            elif isinstance(obj, list):
                # Only keep elements that are strings.
                return [item for item in obj if isinstance(item, str)]
            elif hasattr(obj, '__dict__'):
                # Convert object attributes to dict and only keep strings.
                return {k: v for k, v in vars(obj).items() if isinstance(v, str)}
            return None

        # If the object is a string, simply return it.
        if isinstance(obj, str):
            return obj
        # Recursively process dictionaries.
        elif isinstance(obj, dict):
            filtered = {
                k: v_filtered
                for k, v in obj.items()
                if (v_filtered := filter_strings_only(v, seen, depth + 1, max_depth)) is not None
            }
            return filtered if filtered else None
        # Recursively process lists.
        elif isinstance(obj, list):
            filtered = [
                value
                for item in obj
                if (value := filter_strings_only(item, seen, depth + 1, max_depth)) is not None
            ]
            return filtered if filtered else None
        # Process object attributes if the object has a __dict__.
        elif hasattr(obj, '__dict__'):
            return filter_strings_only(vars(obj), seen, depth + 1, max_depth)
        # For any other types that are not strings or containers, return None.
        return None

    print("\n== Updated Distance Scores (after loading LaTeX content) ==")
    for env in envs_updated:
        new_score = env.get_score() # get_distance_to_targetJSON()
        #print(f"=============================================================\nEnv content of document: <<< {filter_strings_only(env.synthesis_manager.document.document_content, max_depth=3)} >>>\n=============================================================")
        print(f"Updated Env ID: {env.id} -- New Distance Score: {new_score}")

if __name__ == "__main__":
    test_GetFromLatex()

