import re
import json
import requests

from config import MODELS_CONFIG_LIST
from ..human_llm import HumanLLM, HumanLLMConfig
from ..file_utils import load_from_pickle, save_to_pickle


from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage
from langchain_community.document_loaders import WikipediaLoader

from pydantic import BaseModel, Field

llm_custom = ChatOpenAI(model=MODELS_CONFIG_LIST["code_gpt"] if MODELS_CONFIG_LIST else "gpt-4o-mini-2024-07-18", temperature=.0)

class SearchQuery(BaseModel):
    """
    A Pydantic model for the search query input to the search functions.
    """
    search_query: str = Field(None, description="Search query for retrieval.")

def extract_json(data: any) -> dict:
    """
    Extract and return a JSON object from the given input 'data'.

    If 'data' is already a dict or list, it is returned as-is.
    If 'data' is a string:
      - First, it attempts to parse it entirely as JSON.
      - If that fails, it uses two alternative methods:
        
        Method 1: Regex-based extraction.
          - Uses a regex pattern to extract a substring that looks like JSON.
          - Advantage: Very simple and concise.
          - Drawback: It may fail or capture too little/much if the string contains extra text
            or if the JSON has nested structures with inner braces/brackets.

        Method 2: Decoder-based extraction.
          - Iterates over the string and uses JSONDecoder.raw_decode() to try to decode a JSON
            object from positions where a '{' or '[' appears.
          - Advantage: This method leverages the JSON parser’s own grammar, making it more
            robust for nested objects or arrays.
          - Drawback: It may be slightly less intuitive than a one-line regex.

    Returns:
        A parsed JSON object (usually a dict or list).

    Raises:
        ValueError: If no valid JSON can be extracted from the input.
    """
    # If the data is already a dict or list, assume it's valid JSON.
    if isinstance(data, (dict, list)):
        return data

    # Ensure we have a string (if not, convert it).
    if not isinstance(data, str):
        data = str(data)

    data = data.strip()

    # First attempt: Try to parse the whole string as JSON.
    try:
        return json.loads(data)
    except json.JSONDecodeError:
        print("Not a pure JSON string, so we try to extract the JSON part.")

    # --- Method 1: Regex-based extraction ---
    regex_pattern = r'(\{.*\}|\[.*\])'
    match = re.search(regex_pattern, data, re.DOTALL)
    if match:
        candidate = match.group(0)
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            print("If the candidate isn't valid JSON, we try the next method.")

    # --- Method 2: Using JSONDecoder's raw_decode method ---
    decoder = json.JSONDecoder()
    # Iterate over the string; try to decode JSON starting at every '{' or '['.
    for i in range(len(data)):
        if data[i] in ['{', '[']:
            try:
                obj, idx = decoder.raw_decode(data[i:])
                return obj
            except json.JSONDecodeError:
                continue

    # If both methods fail, raise an error.
    print("No valid JSON found in the input data.")

def remove_think_tags(text: str) -> str:
    """
    Remove any ```<think>...</think>``` sections from the given text using regex.
    
    Args:
        text (str): The input string containing potential <think> tags.
    
    Returns:
        cleaned_text (str): The string with all ```<think>...</think>``` sections removed.
    """
    # re.DOTALL allows the dot to match newline characters as well.
    cleaned_text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
    return cleaned_text.strip()

def extract_latex_and_bib_from_llm_output(text: str) -> tuple:
    """
    Extract the LaTeX and BibTeX content from a text generated by an LLM.
    
    Search for:
    1) Either sections "Latex:" and "Bibtex:" followed by their content.
    2) Or Markdown blocks ```latex ... ``` and ```bibtex ... ```.
    
    Returns:
    - latex_str: the properly extracted LaTeX content.
    - bibtex_str: the BibTeX content if it exists, otherwise None.
    """

    # Check if the Markdown format is used
    latex_md_match = re.search(r'```latex\s*([\s\S]*?)\s*```', text, re.IGNORECASE)
    bibtex_md_match = re.search(r'```bibtex\s*([\s\S]*?)\s*```', text, re.IGNORECASE)

    if latex_md_match:
        # Extract the content between the ```latex ... ``` tags
        latex_str = latex_md_match.group(1).strip()
        
        if bibtex_md_match:
            # Extract the content between the ```bibtex ... ``` tags
            bibtex_str = bibtex_md_match.group(1).strip()
        else:
            bibtex_str = None

        return latex_str, bibtex_str

    # Otherwise, fall back to detection using "Latex:" and "Bibtex:"
    lower_text = text.lower()
    
    latex_label = lower_text.find("latex:")
    bibtex_label = lower_text.find("bibtex:")

    if latex_label == -1:
        # If "Latex:" is not found, consider the entire text as LaTeX
        return text.strip(), None

    if bibtex_label == -1:
        # If "Bibtex:" is not found, everything after "Latex:" is LaTeX
        latex_str = text[latex_label + len("Latex:"):].strip()
        return latex_str, None

    # If both labels are found, extract each part
    latex_str = text[latex_label + len("Latex:"):bibtex_label].strip()
    bibtex_str = text[bibtex_label + len("Bibtex:"):].strip()
    
    return latex_str, bibtex_str

@load_from_pickle
@save_to_pickle
def search_llm_query(search_instructions : SystemMessage, user_message : str):
    """
    Call a LLM to define a query to use for searching on web/rag.
    """
    return llm_custom.with_structured_output(SearchQuery).invoke([search_instructions] + user_message)

@load_from_pickle
@save_to_pickle
def search_web_query_get(search_query):
    """
    Search the web for the given query and return the results.
    """
    OPENALEX_API_URL = "https://api.openalex.org/works"
    params = {
        "search": search_query.search_query,  # The search query string generated by the LLM.
        "filter": "is_paratext:false",
        "sort": "relevance_score:desc",
        "per_page": 5
    }
    response = requests.get(OPENALEX_API_URL, params=params)
    search_docs = []

    if response.status_code == 200:
        data = response.json()
        for result in data.get("results", []):
            title = result.get("title") or "Unknown Title"
            abstract = result.get("abstract") or "No abstract available"
            url = result.get("id") or "Not Available"
            authors = ", ".join([auth["author"]["display_name"] for auth in result.get("authorships", [])]) or "Not Available"
            search_docs.append({
                "title": title,
                "authors": authors,
                "abstract": abstract,
                "url": url if url else f"{title}, {authors}"
            })
    else:
        print(f"Error retrieving data from OpenAlex: {response.status_code}")

    # Formatting results for display.
    formatted_search_docs = "\n\n---\n\n".join([
        '<Document title="' + doc["title"] + '" href="' + doc["url"] + '">\nAuthors:' + doc["authors"] + '\n\nAbstract:' + doc["abstract"] + '\n</Document>'
        for doc in search_docs
    ])
    return formatted_search_docs

@load_from_pickle
@save_to_pickle
def search_arxiv_query_get(search_query):
    """
    Search arXiv for the given query and return the results.
    """
    import xml.etree.ElementTree as ET
    ARXIV_API_URL = "http://export.arxiv.org/api/query"
    params = {
        "search_query": search_query.search_query,  # The search query string generated by the LLM.
        "max_results": 5
    }

    response = requests.get(ARXIV_API_URL, params=params)
    search_docs = []

    if response.status_code == 200:
        try:
            root = ET.fromstring(response.content)
            ns = {"atom": "http://www.w3.org/2005/Atom"}
            for entry in root.findall("atom:entry", ns):
                title = entry.find("atom:title", ns).text.strip() if entry.find("atom:title", ns) is not None else "Unknown Title"
                summary = entry.find("atom:summary", ns).text.strip() if entry.find("atom:summary", ns) is not None else "No abstract available"
                link = entry.find("atom:id", ns).text.strip() if entry.find("atom:id", ns) is not None else "Not Available"
                authors = ", ".join([
                    author.find("atom:name", ns).text.strip()
                    for author in entry.findall("atom:author", ns)
                ]) or "Not Available"
                search_docs.append({
                    "title": title,
                    "authors": authors,
                    "summary": summary,
                    "link": link if link else f"{title}, {authors}"
                })
        except Exception as e:
            print(f"Error parsing arXiv XML: {e}")
    else:
        print(f"Error retrieving data from arXiv: {response.status_code}")

    # Formatting results for display.
    formatted_search_docs = "\n\n---\n\n".join([
        '<Document title="' + doc["title"] + '" href="' + doc["link"] + '">\nAuthors:' + doc["authors"] + '\n\nAbstract:' + doc["summary"] + '\n</Document>'
        for doc in search_docs
    ])
    return formatted_search_docs

@load_from_pickle
@save_to_pickle
def search_semantic_scholar_query_get(search_query):
    """
    Search Semantic Scholar for the given query and return the results.
    """
    SEMANTIC_SCHOLAR_API_URL = "https://api.semanticscholar.org/graph/v1/paper/search"
    params = {
        "query": search_query.search_query,  # The search query string generated by the LLM.
        "limit": 5,
        "fields": "paperId,title,abstract,authors"
    }
    response = requests.get(SEMANTIC_SCHOLAR_API_URL, params=params)
    search_docs = []

    if response.status_code == 200:
        data = response.json()
        for paper in data.get("data", []):
            title = paper.get("title") or "Unknown Title"
            abstract = paper.get("abstract") or "No abstract available"
            authors_list = paper.get("authors", [])
            authors = ", ".join([author.get("name", "Unknown") for author in authors_list])
            if not authors:
                authors = "Not Available"
            paper_id = paper.get("paperId")
            url = f"https://www.semanticscholar.org/paper/{paper_id}" if paper_id else "Not Available"
            search_docs.append({
                "title": title,
                "authors": authors,
                "abstract": abstract,
                "url": url if url else f"{title}, {authors}"
            })
    else:
        print(f"Error retrieving data from Semantic Scholar: {response.status_code}")

    # Formatting results for display.
    formatted_search_docs = "\n\n---\n\n".join([
        '<Document title="' + doc["title"] + '" href="' + doc["url"] + '">\nAuthors:' + doc["authors"] + '\n\nAbstract:' + doc["abstract"] + '\n</Document>'
        for doc in search_docs
    ])
    return formatted_search_docs

@load_from_pickle
@save_to_pickle
def search_wikipedia_query_get(search_query):
    """
    Search Wikipedia for the given query and return the results.
    """
    search_docs = WikipediaLoader(query=search_query.search_query, load_max_docs=2).load()
    formatted_search_docs = "\n\n---\n\n".join(
        [
            '<Document source="'+ doc.metadata.get("source", "Not Available") + ' page="' + doc.metadata.get("page", "Not Available") + '"/>\n' + doc.page_content + '\n</Document>'
            for doc in search_docs
        ]
    )
    return formatted_search_docs

@load_from_pickle
@save_to_pickle
def search_docs_rag_get(search_query):
    """
    Search the RAG documents for the given query and return the results.
    """
    search_docs = HumanLLM(agent_name="search_rag", llmORchains_list=HumanLLMConfig().get_llmORchains_list()).get_rag_documents("type", query=search_query.search_query)
    formatted_search_docs = "\n\n---\n\n".join([
        '<Document "' + doc["rag_knowledge"] + '"'
        for doc in search_docs[0]
    ])
    return formatted_search_docs
