import re
import json
import requests
from typing import Optional, List

from config import MODELS_CONFIG_LIST
from utils.human_llm import HumanLLM, HumanLLMConfig
from utils.file_utils import load_from_pickle, save_to_pickle


from langchain_openai import ChatOpenAI
from langchain_core.messages import SystemMessage
from langchain_community.document_loaders import WikipediaLoader

from pydantic import BaseModel, Field

llm_custom = ChatOpenAI(model=MODELS_CONFIG_LIST["code_gpt"] if MODELS_CONFIG_LIST else "gpt-4.1-nano", temperature=.0)

class SearchQuery(BaseModel):
    """
    A Pydantic model for the search query input to the search functions.
    """
    search_query: str = Field(None, description="Search query for retrieval.")

def extract_json(data: any) -> dict:
    """
    Extract and return a JSON object from the given input 'data'.

    If 'data' is already a dict or list, it is returned as-is.
    If 'data' is a string:
      - First, it attempts to parse it entirely as JSON.
      - If that fails, it uses two alternative methods:
        
        Method 1: Regex-based extraction.
          - Uses a regex pattern to extract a substring that looks like JSON.
          - Advantage: Very simple and concise.
          - Drawback: It may fail or capture too little/much if the string contains extra text
            or if the JSON has nested structures with inner braces/brackets.

        Method 2: Decoder-based extraction.
          - Iterates over the string and uses JSONDecoder.raw_decode() to try to decode a JSON
            object from positions where a '{' or '[' appears.
          - Advantage: This method leverages the JSON parser’s own grammar, making it more
            robust for nested objects or arrays.
          - Drawback: It may be slightly less intuitive than a one-line regex.

    Returns:
        A parsed JSON object (usually a dict or list).

    Raises:
        ValueError: If no valid JSON can be extracted from the input.
    """
    # If the data is already a dict or list, assume it's valid JSON.
    if isinstance(data, (dict, list)):
        return data

    # Ensure we have a string (if not, convert it).
    if not isinstance(data, str):
        data = str(data)

    data = data.strip()

    # First attempt: Try to parse the whole string as JSON.
    try:
        return json.loads(data)
    except json.JSONDecodeError:
        print("Not a pure JSON string, so we try to extract the JSON part.")

    # --- Method 1: Regex-based extraction ---
    regex_pattern = r'(\{.*\}|\[.*\])'
    match = re.search(regex_pattern, data, re.DOTALL)
    if match:
        candidate = match.group(0)
        if candidate and candidate[0] in ['{', '[']:
            try:
                return json.loads(candidate)
            except json.JSONDecodeError:
                print("Method 1: Regex-based extraction ---> Not a valid JSON")
            if "\\n" in candidate:
                print("Method 1: Regex-based extraction ---> Trying to replace \\n with newline characters.")
                candidate = candidate.replace("\\n", "\n")
                try:
                    return json.loads(candidate)
                except json.JSONDecodeError:
                    print("Method 1: Regex-based extraction ---> If the candidate isn't valid JSON, we try the next method.")
        else:
            print("Method 1: Regex-based extraction ---> did not match")

    # --- Method 2: Using JSONDecoder's raw_decode method ---
    decoder = json.JSONDecoder()
    # Iterate over the string; try to decode JSON starting at every '{' or '['.
    for i in range(len(data)):
        if data[i] in ['{', '[']:
            try:
                obj, idx = decoder.raw_decode(data[i:])
                # if it is a dict, return obj
                if isinstance(obj, dict):
                    return obj
                continue
            except json.JSONDecodeError:
                continue

    # If both methods fail, raise an error.
    print("No valid JSON found in the input data.")

def remove_think_tags(text: str) -> str:
    """
    Remove any ```<think>...</think>``` sections from the given text using regex.
    
    Args:
        text (str): The input string containing potential <think> tags.
    
    Returns:
        cleaned_text (str): The string with all ```<think>...</think>``` sections removed.
    """
    # re.DOTALL allows the dot to match newline characters as well.
    cleaned_text = re.sub(r'<think>.*?</think>', '', text, flags=re.DOTALL)
    return cleaned_text.strip()

def extract_latex_and_bib_from_llm_output(text: str) -> tuple:
    """
    Extract the LaTeX and BibTeX content from a text generated by an LLM.
    
    Search for:
    1) Either sections "Latex:" and "Bibtex:" followed by their content.
    2) Or Markdown blocks ```latex ... ``` and ```bibtex ... ```.
    
    Returns:
    - latex_str: the properly extracted LaTeX content.
    - bibtex_str: the BibTeX content if it exists, otherwise None.
    """

    # Check if the Markdown format is used
    latex_md_match = re.search(r'```latex\s*([\s\S]*?)\s*```', text, re.IGNORECASE)
    bibtex_md_match = re.search(r'```bibtex\s*([\s\S]*?)\s*```', text, re.IGNORECASE)

    if latex_md_match:
        # Extract the content between the ```latex ... ``` tags
        latex_str = latex_md_match.group(1).strip()
        
        if bibtex_md_match:
            # Extract the content between the ```bibtex ... ``` tags
            bibtex_str = bibtex_md_match.group(1).strip()
        else:
            bibtex_str = None

        return latex_str, bibtex_str

    # Otherwise, fall back to detection using "Latex:" and "Bibtex:"
    lower_text = text.lower()
    
    latex_label = lower_text.find("latex:")
    bibtex_label = lower_text.find("bibtex:")

    if latex_label == -1:
        # If "Latex:" is not found, consider the entire text as LaTeX
        return text.strip(), None

    if bibtex_label == -1:
        # If "Bibtex:" is not found, everything after "Latex:" is LaTeX
        latex_str = text[latex_label + len("Latex:"):].strip()
        return latex_str, None

    # If both labels are found, extract each part
    latex_str = text[latex_label + len("Latex:"):bibtex_label].strip()
    bibtex_str = text[bibtex_label + len("Bibtex:"):].strip()
    
    return latex_str, bibtex_str

@load_from_pickle
@save_to_pickle
def search_llm_query(search_instructions : SystemMessage, user_message : str):
    """
    Call a LLM to define a query to use for searching on web/rag.
    """
    return llm_custom.with_structured_output(SearchQuery).invoke([search_instructions] + user_message)

@load_from_pickle
@save_to_pickle
def search_web_query_get(search_query):
    """
    Search the web for the given query and return the results.
    """
    OPENALEX_API_URL = "https://api.openalex.org/works"
    params = {
        "search": search_query.search_query,  # The search query string generated by the LLM.
        "filter": "is_paratext:false",
        "sort": "relevance_score:desc",
        "per_page": 5
    }
    response = requests.get(OPENALEX_API_URL, params=params)
    search_docs = []

    if response.status_code == 200:
        data = response.json()
        for result in data.get("results", []):
            title = result.get("title") or "Unknown Title"
            abstract = result.get("abstract") or "No abstract available"
            url = result.get("id") or "Not Available"
            authors = ", ".join([auth["author"]["display_name"] for auth in result.get("authorships", [])]) or "Not Available"
            search_docs.append({
                "title": title,
                "authors": authors,
                "abstract": abstract,
                "url": url if url else f"{title}, {authors}"
            })
    else:
        print(f"Error retrieving data from OpenAlex: {response.status_code}")

    # Formatting results for display.
    formatted_search_docs = "\n\n---\n\n".join([
        '<Document title="' + doc["title"] + '" href="' + doc["url"] + '">\nAuthors:' + doc["authors"] + '\n\nAbstract:' + doc["abstract"] + '\n</Document>'
        for doc in search_docs
    ])
    return formatted_search_docs

@load_from_pickle
@save_to_pickle
def search_arxiv_query_get(search_query, max_results=5, excluded_ids = {"2302.09051", "2305.17474"}):
    """
    Search arXiv for the given query and return the results.
    """
    import xml.etree.ElementTree as ET
    ARXIV_API_URL = "http://export.arxiv.org/api/query"
    params = {
        "search_query": search_query.search_query,  # The search query string generated by the LLM.
        "max_results": max_results
    }

    response = requests.get(ARXIV_API_URL, params=params)
    search_docs = []

    if response.status_code == 200:
        try:
            root = ET.fromstring(response.content)
            ns = {"atom": "http://www.w3.org/2005/Atom"}
            for entry in root.findall("atom:entry", ns):
                title = entry.find("atom:title", ns).text.strip() if entry.find("atom:title", ns) is not None else "Unknown Title"
                summary = entry.find("atom:summary", ns).text.strip() if entry.find("atom:summary", ns) is not None else "No abstract available"
                link = entry.find("atom:id", ns).text.strip() if entry.find("atom:id", ns) is not None else "Not Available"
                # Exclude unwanted papers (any version)
                if link.rsplit("/", 1)[-1].split("v", 1)[0] in excluded_ids: continue

                authors = ", ".join([
                    author.find("atom:name", ns).text.strip()
                    for author in entry.findall("atom:author", ns)
                ]) or "Not Available"
                search_docs.append({
                    "title": title,
                    "authors": authors,
                    "summary": summary,
                    "link": link if link else f"{title}, {authors}"
                })
        except Exception as e:
            print(f"Error parsing arXiv XML: {e}")
    else:
        print(f"Error retrieving data from arXiv: {response.status_code}")

    # Formatting results for display.
    formatted_search_docs = "\n\n---\n\n".join([
        '<Document title="' + doc["title"] + '" href="' + doc["link"] + '">\nAuthors:' + doc["authors"] + '\n\nAbstract:' + doc["summary"] + '\n</Document>'
        for doc in search_docs
    ])
    return formatted_search_docs

@load_from_pickle
@save_to_pickle
def search_semantic_scholar_query_get(search_query):
    """
    Search Semantic Scholar for the given query and return the results.
    """
    SEMANTIC_SCHOLAR_API_URL = "https://api.semanticscholar.org/graph/v1/paper/search"
    params = {
        "query": search_query.search_query,  # The search query string generated by the LLM.
        "limit": 5,
        "fields": "paperId,title,abstract,authors"
    }
    response = requests.get(SEMANTIC_SCHOLAR_API_URL, params=params)
    search_docs = []

    if response.status_code == 200:
        data = response.json()
        for paper in data.get("data", []):
            title = paper.get("title") or "Unknown Title"
            abstract = paper.get("abstract") or "No abstract available"
            authors_list = paper.get("authors", [])
            authors = ", ".join([author.get("name", "Unknown") for author in authors_list])
            if not authors:
                authors = "Not Available"
            paper_id = paper.get("paperId")
            url = f"https://www.semanticscholar.org/paper/{paper_id}" if paper_id else "Not Available"
            search_docs.append({
                "title": title,
                "authors": authors,
                "abstract": abstract,
                "url": url if url else f"{title}, {authors}"
            })
    else:
        print(f"Error retrieving data from Semantic Scholar: {response.status_code}")

    # Formatting results for display.
    formatted_search_docs = "\n\n---\n\n".join([
        '<Document title="' + doc["title"] + '" href="' + doc["url"] + '">\nAuthors:' + doc["authors"] + '\n\nAbstract:' + doc["abstract"] + '\n</Document>'
        for doc in search_docs
    ])
    return formatted_search_docs

@load_from_pickle
@save_to_pickle
def search_wikipedia_query_get(search_query):
    """
    Search Wikipedia for the given query and return the results.
    """
    search_docs = WikipediaLoader(query=search_query.search_query, load_max_docs=2).load()
    formatted_search_docs = "\n\n---\n\n".join(
        [
            '<Document source="'+ doc.metadata.get("source", "Not Available") + ' page="' + doc.metadata.get("page", "Not Available") + '"/>\n' + doc.page_content + '\n</Document>'
            for doc in search_docs
        ]
    )
    return formatted_search_docs

# @load_from_pickle
# @save_to_pickle
def search_docs_rag_get(search_query):
    """
    Searches the RAG documents for the given query and returns detailed excerpts using stored metadata.
    Expects each document's metadata to include at least 'title' and 'author' (or 'authors').
    """
    search_docs = HumanLLM(
        agent_name="search_rag", 
        llmORchains_list=HumanLLMConfig().get_llmORchains_list()
    ).get_rag_documents("HumanLLM", query=search_query.search_query)
    
    formatted_search_docs = "\n\n---\n\n".join([
        f'<Document title="{doc.metadata.get("extracted_title", "Unknown Title")}" href="{doc.metadata.get("url", "#")}">\n'
        f'Authors: {doc.metadata.get("extracted_authors", "Unknown Authors")}\n\n'
        f'Excerpt: {doc.page_content or "No excerpt available"}\n'
        f'</Document>'
        for doc in search_docs[1]
    ])
    return formatted_search_docs

def merge_content(existing_section: dict, new_section: dict) -> dict:
    """Merge two section contents while preserving hierarchy"""
    merged = {
        'description': new_section.get('description', existing_section.get('description', '')),
        'sources': list(set(existing_section.get('sources', []) + new_section.get('sources', [])))
    }
    
    # Recursively merge subsections
    if 'subsections' in existing_section or 'subsections' in new_section:
        merged_subsections = existing_section.get('subsections', {}).copy()
        for sub_name, sub_content in new_section.get('subsections', {}).items():
            if sub_name in merged_subsections:
                merged_subsections[sub_name] = merge_content(merged_subsections[sub_name], sub_content)
            else:
                merged_subsections[sub_name] = sub_content
        merged['subsections'] = merged_subsections
    
    return merged

def get_section_data(plan_structure: dict, section_path: str) -> dict:
    """Navigate through plan structure to retrieve section metadata"""
    path_parts = section_path.split('/')
    current_node = plan_structure
    section_data = {}
    
    for part in path_parts:
        if part in current_node:
            section_data = current_node[part]
            current_node = section_data.get('subsections', {})
        else:
            return {}
            
    return {
        'description': section_data.get('description', ''),
        'sources': section_data.get('sources', []),
        'subsections': section_data.get('subsections', {})
    }

MAX_RECURSION_DEPTH = 10

def flatten_plan(plan: dict, parent_path: str = "", depth=0) -> List[str]:
    """Prevent stack overflows in deep hierarchies"""
    if depth > MAX_RECURSION_DEPTH:
        raise RecursionError("Plan hierarchy too deep")
    
    paths = []
    for section, content in plan.items():
        current_path = f"{parent_path}/{section}" if parent_path else section
        paths.append(current_path)
        if 'subsections' in content:
            paths.extend(flatten_plan(content['subsections'], current_path, depth+1))
    return paths

def path_similarity(path1: str, path2: str) -> float:
    """Calculate similarity between section paths using longest common substring"""
    from difflib import SequenceMatcher
    return SequenceMatcher(None, path1, path2).ratio()

def find_similar_section(target_path: str, plan: dict, threshold=0.7) -> Optional[str]:
    """Find most similar existing section path in plan"""
    from difflib import get_close_matches
    existing_paths = flatten_plan(plan)
    matches = get_close_matches(target_path, existing_paths, n=1, cutoff=threshold)
    return matches[0] if matches else None

def merge_plans(old_plan: dict, new_plan: dict, unused_content: dict) -> tuple:
    """Merge previous plan content into new structure with conflict resolution"""
    merged = new_plan.copy()
    unused = unused_content.copy()
    
    # Phase 1: Direct matches
    for old_path in list(old_plan.keys()):
        if old_path in merged:
            # Merge section content
            merged[old_path] = merge_content(old_plan[old_path], merged[old_path])
            # Merge subsections
            merged[old_path]['subsections'] = {
                **old_plan[old_path].get('subsections', {}),
                **merged[old_path].get('subsections', {})
            }
        else:
            unused[old_path] = old_plan[old_path]
    
    # Phase 2: Fuzzy matches
    for old_path in list(unused.keys()):
        similar_path = find_similar_section(old_path, merged)
        if similar_path:
            merged[similar_path] = merge_content(merged[similar_path], unused.pop(old_path))
    
    # Phase 3: Preserve orphaned content
    for old_path, content in unused.items():
        merged.setdefault('_orphaned', {})[old_path] = content
    
    return merged, unused

def initialize_content_sections(new_plan: dict, state: dict) -> dict:
    """Initialize content sections with previous content where possible"""
    content = {}
    # Flatten plan structure
    for section_path in flatten_plan(new_plan):
        # Try to find matching content from previous iterations
        matched = False
        for prev_path in state.get("content_sections", {}):
            if path_similarity(prev_path, section_path) > 0.8:  # Threshold for auto-matching
                content[section_path] = state["content_sections"][prev_path]
                matched = True
                break
        if not matched:
            content[section_path] = ""
    return content