name: Run Script Manually

on:
  workflow_dispatch: # This allows manual triggers from the GitHub Actions UI.

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from the branch
      uses: actions/checkout@v3
      with:
        ref: feature-branch # Replace with the branch name you want

    - name: Create config.py file
      run: |
        cat <<EOL > ${{ github.workspace }}/config.py
        import os
        # Check the docker environment variables to see if LLM_MODE is set (to launch on a cluster/macstudio using ollama)
        IN_MACSTU = os.environ.get('LLM_MODE')
        if IN_MACSTU in ["macstudio", "gpu"]:
            os.environ['OPENAI_BASE_URL'] = 'http://localhost:11434/v1'
            OPENAI_API_KEY = "ollama"
            if IN_MACSTU == "macstudio":
                MODELS_CONFIG_LIST = {
                        "basic_gpt":"codestral_latest_20k:latest",
                        "smart_gpt":"codestral_latest_20k:latest",
                        "code_gpt":"codestral_latest_20k:latest",
                }
            else:
                MODELS_CONFIG_LIST = {
                        "basic_gpt":"codestral:latest-20k",
                        "smart_gpt":"codestral:latest-20k",
                        "code_gpt":"codestral:latest-20k",
                }
        else:
            OPENAI_API_KEY = ${{ secrets.OPENAI_API_KEY }}
            MODELS_CONFIG_LIST = {
                "code_gpt": "gpt-4o-mini-2024-07-18",
                "smart_gpt": "gpt-4o-mini-2024-07-18",
                "basic_gpt": "gpt-4o-mini-2024-07-18",
            }
        openai_api_key = OPENAI_API_KEY
        os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY

        # Elastic search and Kibana information
        elastic_url_port = 'http://localhost:9200'
        kibana_url_port = 'http://localhost:5601'
        elastic_user=""
        elastic_password=""
        PickleCacheActivated = False

        # Neo4j database information
        NEO4J_URI = 'URI_of_your_neo4j_database'
        NEO4J_USER = 'neo4j_user'
        NEO4J_PASSWORD = 'neo4j_password'
        EOL

    - name: Pull Docker Image
      run: docker pull jitaross/ollamawithpython

    - name: Run Docker Container with mounted code
      run: docker run -v ${{ github.workspace }}:/workspace jitaross/ollamawithpython python /workspace/learn.py --secret --proxy
