name: Automated Tests for CollabFunctionGPTCreator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      NON_SECRET_VARIABLE: "some_value"
      # Add other environment variables as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

     # Cache pip dependencies
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    # Cache Docker images
    - name: Cache Docker images
      id: docker_cache
      uses: actions/cache@v3
      with:
        path: docker_image_cache
        key: ${{ runner.os }}-docker-${{ hashFiles('**/docker-compose.yml') }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Load Docker images from cache
      if: steps.docker_cache.outputs.cache-hit == 'true'
      run: |
        if [ -d docker_image_cache ]; then
          for image in docker_image_cache/*.tar; do
            docker load -i "$image"
          done
        fi

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y scrot

    - name: Create config.py
      run: |
        cat <<EOF > config.py
        import os
        OPENAI_API_KEY = "${{ secrets.OPENAI_API_KEY }}"
        MODELS_CONFIG_LIST = {
            "code_gpt": "gpt-4o-mini-2024-07-18",
            "smart_gpt": "gpt-4o-mini-2024-07-18",
            "basic_gpt": "gpt-4o-mini-2024-07-18"
            }
        openai_api_key = OPENAI_API_KEY
        os.environ['OPENAI_API_KEY'] = OPENAI_API_KEY
        elastic_url_port = 'http://localhost:9200'
        kibana_url_port = 'http://localhost:5601'
        elastic_user=''
        elastic_password=''
        PickleCacheActivated = False
        EOF

    - name: Start Elasticsearch
      run: |
        cd elasticsearch
        docker-compose up -d

    - name: Wait for Elasticsearch to be ready
      run: |
        for i in {1..10}; do
          if curl -s http://localhost:9200 >/dev/null; then
            echo "Elasticsearch is up!"
            break
          else
            echo "Waiting for Elasticsearch to start..."
            sleep 5
          fi
        done

    - name: Run Selenium script and capture logs
      run: |
        nohup python learn.py > learn_logs.txt

    - name: Execute run_multi.sh and capture logs
      run: |
        bash run_multi.sh optuna_opti_Synthesis_coder GPT4 &
        sleep 120
        kill $!

    - name: Collect and Upload logs
      run: |
        mkdir -p logs_and_screenshots
        cp logs/*.log logs_and_screenshots/ || true
        cp screenshots/*.png logs_and_screenshots/ || true

    - name: Upload logs and screenshots
      uses: actions/upload-artifact@v3
      with:
        name: logs-and-screenshots
        path: logs_and_screenshots

    - name: Stop Elasticsearch
      if: always()
      run: |
        cd elasticsearch
        docker-compose down

    - name: Logs of learn.py execution
      run: |
        cat learn_log.txt
