name: Automated Tests for CollabFunctionGPTCreator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get install firefox-geckodriver scrot

    - name: Run Selenium script and capture logs
      run: |
        nohup python learn.py &
        python test_collabfunction.py

    - name: Execute run_multi.sh and capture logs
      run: |
        bash run_multi.sh optuna_opti_Synthesis_coder GPT4 &
        sleep 120  # Run the script for 2 minutes
        kill $!  # Stop the process

    - name: Collect and Upload logs
      run: |
        mkdir -p logs_and_screenshots
        cp logs/*.log logs_and_screenshots/
        cp screenshots/*.png logs_and_screenshots/

    - name: Upload logs and screenshots
      uses: actions/upload-artifact@v3
      with:
        name: logs-and-screenshots
        path: logs_and_screenshots
