name: Automated Tests for CollabFunctionGPTCreator

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # Add other environment variables as needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      with:
        cache: 'pip' # Caching pip dependencies
      run: |
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y scrot

    - name: Set up configuration
      run: |
        cp config_template.py config.py

    - name: Configure settings in config.py
      run: |
        # Replace placeholders with environment variables
        sed -i 's/your_placeholder_api_key/'"$OPENAI_API_KEY"'/' config.py
        # Add additional sed commands for other configurations if necessary

    - name: Run Selenium script and capture logs
      run: |
        nohup python learn.py &
        python test_collabfunction.py

    - name: Execute run_multi.sh and capture logs
      run: |
        bash run_multi.sh optuna_opti_Synthesis_coder GPT4 &
        sleep 120  # Run the script for 2 minutes
        kill $!  # Stop the process

    - name: Collect and Upload logs
      run: |
        mkdir -p logs_and_screenshots
        cp logs/*.log logs_and_screenshots/ || true
        cp screenshots/*.png logs_and_screenshots/ || true

    - name: Upload logs and screenshots
      uses: actions/upload-artifact@v4
      with:
        name: logs-and-screenshots
        path: logs_and_screenshots
